version: '3.9'
services:
  orthanc-server:
    image: jodogne/orthanc-plugins
    container_name: orthanc-server
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    depends_on:
      - postgres
    ports:
      - 4242:4242
      - 8042:8042
    restart: on-failure

  postgres:
    image: postgres:12.5
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_DB: orthanc
      POSTGRES_PASSWORD: orthanc
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    restart: on-failure

  dicom-client:
    build:
      context: ./sender
    volumes:
      - ./sender/dicoms:/dicoms
    depends_on:
      - orthanc-server

volumes:
  postgres-data: