version: '3.9'

services:
  postgres:
    image: postgres:12.5
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: othanc
      POSTGRES_DB: othanc
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  postgres-data: